### ISSUE TITLE
Can you compile your c++ code to webassembly or maybe asm.js / pure js so I can use the library of bable in my websites for fun too

### ISSUE THREAD

**Issue by Xyncgas** [librarianofbabel/libraryofbabel.info-algo#1]

**Comment by Xyncgas** [comment]
Although for all seriousness I am trying to build something useful, for myself right n, I admire how glorious such experiment of yours was able to get it worked because it's such unimaginable to be generating a random page and search in there I mean it's so many possibilities and how is the processor even fast enough!!!

**Comment by Xyncgas** [comment]
That is if I had it right after reading the theory on libraryofbabel.info or maybe I had it wrong, that the text actually weren't stored and it was generated dynamically through rng, so how can it be so fast?

**Comment by Xyncgas** [comment]
let me guess, the program is actually being hosted on the server, that's why it's so fast even when I underclocked my cpu.

**Comment by Xyncgas** [comment]
never mind I am gonna try to do it myself, was definitely nice to be the #1 issue.

**Comment by drake90001** [comment]
howd it go bud
